### ISSUE TITLE
ValueError: cannot fit 'int' into an offset-sized integer

### ISSUE THREAD

**Issue by doomedraven** [DissectMalware/pyOneNote#1]
Hello. Nice new tool :)
I got the sample from your twit 835239c095e966bf6037f5755b0c4ed333a163f5cc19ba0bc50ea3c96e0f1628
https://twitter.com/DissectMalware/status/1622426990400913408

I have tried it on ubuntu 20 with python 3.8 and MacOS with python 3.10.9

here details if that helps. let me know if i can help you fix this issue
```
python3 main.py malware.one
Python 3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> header.fcrFileNodeListRoot
FileChunkReference64x32:(stp:15445885444106945343, cb:2670629520)
```

```
>>> root_file_node_list = FileNode.FileNodeList(file, header.fcrFileNodeListRoot)
15445885444106945343
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/Do_Not_Scan/github/public/pyOneNote/FileNode.py", line 13, in __init__
    file.seek(file_chunk_reference.stp)
ValueError: cannot fit 'int' into an offset-sized integer

```

**Comment by doomedraven** [comment]
could it be that python is x64 and not x32 bits?

**Comment by doomedraven** [comment]
Ups, my fail
