### ISSUE TITLE
AttributeError: 'FileNode' object has no attribute 'data'

### ISSUE THREAD

**Issue by albertzsigovits** [DissectMalware/pyOneNote#4]
Hi @DissectMalware @doomedraven ,
thanks for your efforts on this.

Found the following bug:
Test case: `f408ef3fa89546483ba63f58be3f27a98795655eb4b9b6217cbe302a5ba9d5f7`

```
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    process_onenote_file(file, output_dir, extension)
  File "main.py", line 86, in process_onenote_file
    root_file_node_list = FileNode.FileNodeList(file, header.fcrFileNodeListRoot)
  File "/tmp/pyOneNote/FileNode.py", line 19, in __init__
    fragment = FileNodeListFragment(file, section_end)
  File "/tmp/pyOneNote/FileNode.py", line 34, in __init__
    node = FileNode(file)
  File "/tmp/pyOneNote/FileNode.py", line 154, in __init__
    self.children.append(FileNodeList(file, self.data.ref))
  File "/tmp/pyOneNote/FileNode.py", line 19, in __init__
    fragment = FileNodeListFragment(file, section_end)
  File "/tmp/pyOneNote/FileNode.py", line 34, in __init__
    node = FileNode(file)
  File "/tmp/pyOneNote/FileNode.py", line 154, in __init__
    self.children.append(FileNodeList(file, self.data.ref))
  File "/tmp/pyOneNote/FileNode.py", line 19, in __init__
    fragment = FileNodeListFragment(file, section_end)
  File "/tmp/pyOneNote/FileNode.py", line 34, in __init__
    node = FileNode(file)
  File "/tmp/pyOneNote/FileNode.py", line 154, in __init__
    self.children.append(FileNodeList(file, self.data.ref))
AttributeError: 'FileNode' object has no attribute 'data'
```

**Comment by DissectMalware** [comment]
Thank you for reporting this error. However it's already fixed in https://github.com/DissectMalware/pyOneNote/tree/test.

**Comment by DissectMalware** [comment]
Leave it open so if other have the same problem see my comment. 

The branch will be merged as soon as it covers a good percentage of onenote files (meaning covering more FileNode types)
